### ISSUE TITLE
Track tiles textures in "Gare d'europa" and "Spliskinanke" are incorrect (default texture is shown)

### ISSUE THREAD

**Issue by tigrouind** [phoboslab/wipeout#15]
In  "Gare d'europa" and "Spliskinanke" tracks, incorrect texture (a checker pattern) is used for the whole track. It seems  the texture index read from game files is always "0" for these two ones . Because of this there is also no power ups (weapons or boost tiles). Why these two tracks seems to use a different way to store texture track than other tracks and where that information is stored is actually unknown.

**Comment by wp9015362** [comment]
@tigrouind :

I have already reported this issue some days ago, see:

https://github.com/phoboslab/wipeout/issues/6

Regards

**Comment by tigrouind** [comment]
Yes you are right. You can close the issue (or even better : delete it if possible)
