### ISSUE TITLE
More music?

### ISSUE THREAD

**Issue by wp9015362** [phoboslab/wipeout#5]
Hello,

currently the viewer has only one music track.

Would there be any chance you could add some more?

Regards

**Comment by JALsnipe** [comment]
This isn't an issue with the code per-say, but a licensing issue.

If you want more tracks, clone the project and run it yourself with more tracks in the `soundtrack/` folder.

**Comment by phoboslab** [comment]
Agreed. While you can listen to the WipEout Cold Storage tracks on lastfm (http://www.lastfm.de/music/Cold+Storage?ac=cold+storage), there's no license information on these as far as I can see.

This repository should not include any game data to evade any copyright questions. As for the demo on phoboslab: I'm still somewhat surprised I haven't gotten a takedown request from Sony, but I don't want to test my luck any further.
